import { Assignment, AttendanceRecord, Course, Message, SchoolDocument, Student } from "@/types";
export const student:Student={id:"tobias",name:"Tobias",gradeLevel:"11th grade"};
const assignments=(courseId:string, rows:[string,string,string,number|null,number,Assignment["status"]][]):Assignment[]=>rows.map((r,i)=>({id:`${courseId}-${i}`,courseId,name:r[0],category:r[1],dueDate:r[2],score:r[3],possiblePoints:r[4],status:r[5]}));
export const courses:Course[]=[
 {id:"calc",name:"AP Calculus BC",teacher:"Ms. Patel",color:"#5b5ce2",courseType:"AP",credits:1,categories:[{name:"Tests",weight:50},{name:"Homework",weight:20},{name:"Projects",weight:20},{name:"Quizzes",weight:10}],assignments:assignments("calc",[["Unit 3 Test","Tests","Aug 28",94,100,"Completed"],["Related Rates Set","Homework","Aug 30",20,20,"Completed"],["Taylor Series Quiz","Quizzes","Sep 2",null,20,"Upcoming"],["Optimization Lab","Projects","Aug 25",null,50,"Missing"]])},
 {id:"japanese",name:"AP Japanese",teacher:"Mr. Watanabe",color:"#ea7b5b",courseType:"AP",credits:1,categories:[{name:"Assessments",weight:45},{name:"Practice",weight:35},{name:"Culture",weight:20}],assignments:assignments("japanese",[["Kanji Check 4","Practice","Aug 29",18,20,"Completed"],["Oral Reflection","Assessments","Sep 1",45,50,"Completed"],["Culture Journal","Culture","Sep 3",null,25,"Upcoming"]])},
 {id:"gov",name:"AP Government",teacher:"Dr. Ellis",color:"#37a77b",courseType:"AP",credits:1,categories:[{name:"Tests",weight:45},{name:"Writing",weight:30},{name:"Daily Work",weight:25}],assignments:assignments("gov",[["Federalism FRQ","Writing","Aug 26",44,50,"Completed"],["Unit 1 Exam","Tests","Aug 30",null,100,"Upcoming"],["Court Case Notes","Daily Work","Aug 27",10,10,"Late"]])},
 {id:"physics",name:"Physics",teacher:"Ms. Chen",color:"#318bbd",courseType:"Honors",credits:1,categories:[{name:"Labs",weight:35},{name:"Tests",weight:40},{name:"Practice",weight:25}],assignments:assignments("physics",[["Vectors Lab","Labs","Aug 24",47,50,"Completed"],["Motion Problem Set","Practice","Aug 31",null,20,"Upcoming"]])},
 {id:"lit",name:"British Literature",teacher:"Mrs. Owens",color:"#b7679f",courseType:"Honors",credits:1,categories:[{name:"Essays",weight:40},{name:"Reading",weight:35},{name:"Discussion",weight:25}],assignments:assignments("lit",[["Beowulf Analysis","Essays","Aug 27",92,100,"Completed"],["Reading Check","Reading","Aug 29",19,20,"Completed"]])},
 {id:"eng",name:"Engineering",teacher:"Mr. Diaz",color:"#c59535",courseType:"Regular",credits:1,categories:[{name:"Builds",weight:50},{name:"Design",weight:30},{name:"Practice",weight:20}],assignments:assignments("eng",[["Bridge Prototype","Builds","Aug 26",48,50,"Completed"],["CAD Sketches","Design","Aug 30",null,25,"Upcoming"]])}
];
export const attendance:AttendanceRecord[]=Array.from({length:20},(_,i)=>({date:`Aug ${i+1}`,status:i===7?"absence":i===14?"tardy":"present"}));
export const documents:SchoolDocument[]=[{id:"r",name:"Progress Report",date:"Aug 22, 2026",type:"Academic"},{id:"t",name:"Unofficial Transcript",date:"Aug 18, 2026",type:"Academic"},{id:"s",name:"Fall Schedule",date:"Aug 11, 2026",type:"Schedule"}];
export const messages:Message[]=[{id:"1",sender:"Ms. Patel",subject:"Optimization lab feedback",preview:"Nice work on your solution strategy…",date:"Today",unread:true,body:"Nice work on your solution strategy. Please stop by if you want to review the final step."},{id:"2",sender:"Counseling Office",subject:"College night reminder",preview:"Join us Thursday at 6pm…",date:"Yesterday",unread:false,body:"Join us Thursday at 6pm in the auditorium for College Night."}];
